# GitHub Actions workflow for deploying a Node.js application to Azure Web App

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ivas-tileserver    # Application name in Azure
  AZURE_WEBAPP_PACKAGE_PATH: '.'       # Path to the web app project
  NODE_VERSION: '20.x'                 # Node.js version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install dependencies for OpenGL if needed
      - name: Install libOpenGL
        run: sudo apt-get update && sudo apt-get install libopengl0 -y

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Install Node.js dependencies
      - name: npm install, build, and test
        run: |
          npm install

      # Deploy to Azure WebApp
      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
